version: '2'
services:
    odontologia-app:
        image: odontologia
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://odontologia-mysql:3306/odontologia?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://odontologia-elasticsearch:9200
        ports:
            - 8080:8080
    odontologia-mysql:
        extends:
            file: mysql.yml
            service: odontologia-mysql
    odontologia-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: odontologia-elasticsearch
